### ISSUE TITLE
Problem with detecting civilized populations

### ISSUE THREAD

**Issue by boskoramen** [Kromtec/LegendsViewer#20]
If a civilized race's plural name in the [NAME] token does not end in **s**, it is considered a part of **Other Populations** rather than **Civilized Populations**.

An example of this is my modded race, the mandre.

Functioning plurals:

- mandres
- mandhasdfhlsdahfkhskjhksdhhs
- ms

Non-functioning plurals:

- mandre
- mandren
- s

**Comment by Kromtec** [comment]
Thanks for reporting, I will look into it.

**Comment by Kromtec** [comment]
with the newest creature_raw section in legends_plus.xml this issue should be fixed
