### ISSUE TITLE
Lazy Newb Pack link in the last release notes is phishing site.

### ISSUE THREAD

**Issue by isaacwhanson** [Kromtec/LegendsViewer#43]
the lazynewbpack .com link in the release notes from yesterday resolves to a phishing site.

**Comment by Kromtec** [comment]
That is aweful! This link pointed to the right page a few years ago. It is not only in the release notes, but everywhere, from Legends Viewer startpage to almost every changelog I posted in the last few years. :grimacing:

**Comment by Kromtec** [comment]
Fixed in version 1.20.02
