### ISSUE TITLE
Crash with report using LegendsViewer-1.20.02 with 47.03 export data.

### ISSUE THREAD

**Issue by clinodev** [Kromtec/LegendsViewer#45]
Hey there!

So, I was looking to include this in the little W64 mini-Pack I've been making as new releases come out. To test it first, I used open-legends and exportlegends -all through dfhack-0.47.03-alpha0-200218004-Windows-64. All that went fine. 

When I tried to import the data, it seemed fine, but then:
![Screenshot (65)](https://user-images.githubusercontent.com/9649547/74886076-2feafe80-5345-11ea-9b7b-4291b7c1058f.png)

with

[LegendsViewerCrash.txt](https://github.com/Kromtec/LegendsViewer/files/4228014/LegendsViewerCrash.txt)

Continue just crashed LegendsViewer to desktop.

Hope this helps!

**Comment by Kromtec** [comment]
Thanks for reporting. Can you provide the exported XMLs in a zip file? I think I already found the error, but it would be cool to verify.

**Comment by clinodev** [comment]
Sure!
[clinodev XMLs.zip](https://github.com/Kromtec/LegendsViewer/files/4229566/clinodev.XMLs.zip)

**Comment by Kromtec** [comment]
Will be fixed in the upcoming version, thanks!
