### ISSUE TITLE
The animated creatures shown as 'Necromancer' in charts

### ISSUE THREAD

**Issue by AngelicosPhosphoros** [Kromtec/LegendsViewer#49]
Example: 
![изображение](https://user-images.githubusercontent.com/13154246/76201908-141c9f00-6205-11ea-9f25-21fe13c170ec.png)

The event log says: "In 74, midsummer,  (1st of Galena) Imimi was brought back from the dead by the dwarf necromancer Kumil Springtomes in The Mute Hill."

The save export here:
[ForLegends_2.zip](https://github.com/Kromtec/LegendsViewer/files/4305889/ForLegends_2.zip)

**Comment by Kromtec** [comment]
Thanks for reporting, I will fix this in the next version.

**Comment by Kromtec** [comment]
Fixed in 1.20.04
