### ISSUE TITLE
A crash occuring in the recent version

### ISSUE THREAD

**Issue by artemsmikh** [Kromtec/LegendsViewer#55]
Hey, I just noticed an error when importing my world info exported by the DFhack `exportlegends info` command.

The error is this:

![Screenshot 2020-08-14 at 03 32 34](https://user-images.githubusercontent.com/5757193/90199951-d25cd980-ddde-11ea-8308-8f3adbe9b2ce.png)

The exported files are attached.

[legends-region2-00200-11-09.zip](https://github.com/Kromtec/LegendsViewer/files/5072105/legends-region2-00200-11-09.zip)

Thanks!

**Comment by artemsmikh** [comment]
As I can see, it happens because in the file [CreateEntityPosition.cs](https://github.com/Kromtec/LegendsViewer/blob/master/LegendsViewer/Legends/Events/CreateEntityPosition.cs) the `Reason` variable is expected to be `int`, when in fact is a `string` with the next possible values:
```
"force_of_argument"
"threat_of_violence"
"collaboration"
"wave_of_popular_support"
"as_a_matter_of_course"
```

**Comment by artemsmikh** [comment]
Can't say if it is a bug, or in the past, the `<reason>` tag used to have an int value. But for me changing the `Reason` variable type to string and the appropriate switch case to check against the string values solved the case.

Also, the same thing happened with `InjuryType` variable (file HFWounded.cs), `Action` (file EntityRelocate.cs), `Action` (file EntityPrimaryCriminals.cs), `Action` (file HFProfanedStructure.cs). All there variables now have a string value in the plus xml file.

**Comment by Kromtec** [comment]
Looks like DFHack updated some exported properties. Thanks, I will look into it.

**Comment by Kromtec** [comment]
will be fixed with the next release 😉

**Comment by artemsmikh** [comment]
Great! Looking forwarf to it
